### ISSUE TITLE
error on loading

### ISSUE THREAD

**Issue by frkwhiteangel** [bsalex/angular-loading-overlay#7]
Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module airport due to:
Error: [$injector:modulerr] Failed to instantiate module bsLoadingOverlay due to:
Error: [$injector:nomod] Module 'bsLoadingOverlay' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=bsLoadingOverlay
    at http://178.62.5.64:3000/lib/angular/angular.js:68:12
    at http://178.62.5.64:3000/lib/angular/angular.js:2082:17
    at ensure (http://178.62.5.64:3000/lib/angular/angular.js:2006:38)
    at module (http://178.62.5.64:3000/lib/angular/angular.js:2080:14)
    at http://178.62.5.64:3000/lib/angular/angular.js:4617:22
    at forEach (http://178.62.5.64:3000/lib/angular/angular.js:321:20)
    at loadModules (http://178.62.5.64:3000/lib/angular/angular.js:4601:5)
    at http://178.62.5.64:3000/lib/angular/angular.js:4618:40
    at forEach (http://178.62.5.64:3000/lib/angular/angular.js:321:20)
    at loadModules (http://178.62.5.64:3000/lib/angular/angular.js:4

**Comment by bsalex** [comment]
Hi, thanks for the report.

Did you include the module script?
Are you using some module loader or bundler?

**Comment by frkwhiteangel** [comment]
no, im only useing this script.
im using module. could we chat?
